### ISSUE TITLE
just a quick q

### ISSUE THREAD

**Issue by kaseykwong** [kaseykwong/bme590final#15]
not really an issue but also gotta seem like we're using github to communicate. Are you gonna be separating the files into the separate days or is that more on the server/database/my end? and also are we going to use local machine folder or a "cloud" database to store everything?

**Comment by liameirose** [comment]
Hey, I think it would be easier to do it in the import_data file? What do you think?

Also, I was just trying it out because that is the way he does it now? But I think we should do the cloud database to store everything though. It is better than his current storage method of operation.

**Comment by kaseykwong** [comment]
Yeah I think it makes sense to do it in the import_data. We can figure out the format of the files/folders so I can properly make the database storage stuff. 
Yeah cloud database makes sense. I already created a new Mongodb database which should appear whenever I commit my new stuff

**Comment by liameirose** [comment]
Yeah I just don't know how to format everything file/folder wise. Because should I jasonify each .bin file or???

And okay cool, I will take a look at it when you do.
