### ISSUE TITLE
Cannot automatically merge branch with master (Slack conversation)

### ISSUE THREAD

**Issue by liameirose** [kaseykwong/bme590final#19]
Trying to merge improve_import branch but changes have been made to the requirements document by multiple people so GitHub will not allow an automatic merge.

**Comment by mlp6** [comment]
Do (did?) you have a Pull Request open that demonstrated the conflict?

**Comment by liameirose** [comment]
Yeah I did, but it's not there. I will put it back up!

**Comment by liameirose** [comment]
It is under branches and when I try to make a new pull request it still pops up with cannot automatically merge

**Comment by mlp6** [comment]
Hmmmm... I'm still not seeing an open PR... which two branches are you trying to merge?

**Comment by liameirose** [comment]
Should I still go ahead and create the pull request even though they can't merge automatically?

**Comment by liameirose** [comment]
And master and improve_import

**Comment by liameirose** [comment]
Got it figured out. Thank you.
