### ISSUE TITLE
pyusb library install help

### ISSUE THREAD

**Issue by liameirose** [kaseykwong/bme590final#21]
OS: High Sierra 10.13.6

**Comment by liameirose** [comment]
Looking at some of the threads online, it looks like installing homebrew may help. Would this be a good step in the right direction?

**Comment by mlp6** [comment]
Oh yes... `homebrew` is definitely a good--almost necessary--starting point for installing Mac OS  packages.  I had assumed that was already part of your workflow... not good to make assumptions.  ;)

**Comment by liameirose** [comment]
Haha, whoops! But I figured out how to detect devices using subprocess in python. So no need for homebrew or a library. Hopefully this helps other groups too :) thanks!
