### ISSUE TITLE
Checking that inputs are correct type

### ISSUE THREAD

**Issue by kaseykwong** [kaseykwong/bme590final#32]
For saving each file into the database, I am currently using different fields to store pin#, date, time recorded etc. Since the date and time of file creation information is coming directly from the information in the BIN file, is it necessary to test that these inputs are the correct datetime types if there should be no way that someone could manually change these parameters into, for example, a word or random number?

**Comment by mlp6** [comment]
You just want to check that the values are properly being read from the binary files.
