### ISSUE TITLE
Clarification about logging 

### ISSUE THREAD

**Issue by sharonsangermano** [kaseykwong/bme590final#42]
Looking over the project requirements again.  For the point about post-download log reports specifically -- "Stand-alone log reporting. Client may use software to check what data has been downloaded for a given PIN, range of PINs, date, and range of dates (dates corresponding to when data was collected on the field, not downloaded)."  -- does that mean the GUI should have an option that allows the user to search stored data via PINs/Date and a GET method with the server?  Or would just having this information in a log file be sufficient?

**Comment by mlp6** [comment]
The latter... just having the information in a log that can be opened/searched if needed is adequate.

**Comment by sharonsangermano** [comment]
Perfect, thank you!
